import { Timestamp } from 'firebase/firestore';
export interface Product {
      //Auto Generated By Cloud Function
  id?: string;
  createdAt?: Timestamp;
  createdDate?: string;
  createdBy?: string;

  brand?: string;
  name?: string;
  imgURL?:string;
  price?:string;
  detail?:string
}